### ISSUE TITLE
ENHANCEMENT: Add a license to the repo

### ISSUE THREAD

**Issue by concertman** [tomoconnor/logstash_cleanout#1]
If you’d like others to use this (which I would) it would be helpful to add an OSS license such as Apache or MIT to the repo. Some groups, such as mine, can’t use OSS unless there is a license attached.

Thanks for sharing this script!

**Comment by tomoconnor** [comment]
https://github.com/tomoconnor/logstash_cleanout/blob/master/LICENSE.md

Done :+1:

**Comment by concertman** [comment]
awesome thanks! +1 for MIT
